# Generated by Django 4.2.6 on 2023-12-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0058_recurring_bills_vendor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring_bills',
            name='vendor_email',
        ),
    ]
