# Generated by Django 4.2.6 on 2023-12-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0059_remove_recurring_bills_vendor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bills',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
