# Generated by Django 4.2.6 on 2024-01-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0061_purchasebills_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebills',
            name='reference_numbr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='order_numb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='reference_numb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
