# Generated by Django 4.2.6 on 2024-01-03 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0062_purchasebills_reference_numbr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebills',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.company_details'),
        ),
    ]
