# Generated by Django 4.2.6 on 2024-01-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0063_purchasebills_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebills',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasebills',
            name='cheque_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasebills',
            name='upi_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='cheque_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='upi_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
